name: Test latest tailscale features

on:
  workflow_dispatch:

jobs:
  run-tailscale-script:
    runs-on: ubuntu-latest
    # optional: adjust timeout if your runner allows longer jobs
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tailscale script
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          chmod +x ./script.sh
          ./script.sh
        shell: bash
